# Generated by Django 5.2 on 2025-05-25 18:32

import django.utils.timezone
import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('ID_Beneficiario', models.IntegerField(default=pacientes.models.gerar_id_unico, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('Data_Nascimento', models.DateField()),
                ('Endereco', models.TextField()),
                ('Telefone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Data_Cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
