# Generated by Django 5.2 on 2025-06-07 16:26

import django.core.validators
import django.utils.timezone
import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='CPF',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter apenas números')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='Data_Cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='Data_Nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='Endereco',
            field=models.TextField(verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ID_Beneficiario',
            field=models.IntegerField(default=pacientes.models.gerar_id_unico, editable=False, unique=True, verbose_name='ID do Beneficiário'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='Nome',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='Telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
